apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: authcodes.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: AuthCode
      listKind: AuthCodeList
      plural: authcodes
      singular: authcode
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: authrequests.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: AuthRequest
      listKind: AuthRequestList
      plural: authrequests
      singular: authrequest
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: connectors.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: Connector
      listKind: ConnectorList
      plural: connectors
      singular: connector
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: devicerequests.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: DeviceRequest
      listKind: DeviceRequestList
      plural: devicerequests
      singular: devicerequest
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: devicetokens.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: DeviceToken
      listKind: DeviceTokenList
      plural: devicetokens
      singular: devicetoken
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: oauth2clients.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: OAuth2Client
      listKind: OAuth2ClientList
      plural: oauth2clients
      singular: oauth2client
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: offlinesessionses.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: OfflineSessions
      listKind: OfflineSessionsList
      plural: offlinesessionses
      singular: offlinesessions
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: passwords.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: Password
      listKind: PasswordList
      plural: passwords
      singular: password
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: refreshtokens.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: RefreshToken
      listKind: RefreshTokenList
      plural: refreshtokens
      singular: refreshtoken
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  metadata:
    labels:
      app: dbot-dex
      project: dbot
    name: signingkeies.dex.coreos.com
  spec:
    conversion:
      strategy: None
    group: dex.coreos.com
    names:
      kind: SigningKey
      listKind: SigningKeyList
      plural: signingkeies
      singular: signingkey
    scope: Namespaced
    versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
kind: List
metadata:
  resourceVersion: ""
