{{ $global := .Values.dbot.global -}}
{{ $values := .Values.dbot.workflowcontroller -}}
  {{- if $values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbot-workflow-controller
  labels:
    app: dbot-workflow-controller
    project: dbot
  namespace: dbot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
     matchLabels:
        app: dbot-workflow-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dbot-workflow-controller
        project: dbot
    spec:
      containers:
        - name: dbot-workflow-controller
          image: "{{ $global.image.repo }}/dbot-controller:{{ $global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command:
            - "dbot"
          args:
            - "wc"
            - "start"
          env:
            - name: RABBITMQ_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: host
                  name: rabbitmq-credentials
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: rabbitmq-credentials
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: rabbitmq-credentials
            {{- toYaml $values.env | nindent 12 }}
          resources:
            {{- toYaml $values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      imagePullSecrets:
        - name: registry-credentials
      serviceAccountName: dbot-workflow-controller
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
  {{- end }}