---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dbot-controller-credentials
spec:
  backendType: vault
  data:
  - key: kv/data/dbot/controller-credentials
    name: HOOK_SERVICE_TOKEN
    property: HOOK_SERVICE_TOKEN
  - key: kv/data/dbot/controller-credentials
    name: CONTROLLER_GITLAB_API_TOKEN
    property: CONTROLLER_GITLAB_API_TOKEN
  kvVersion: 2

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dex-saml
spec:
  backendType: vault
  data:
  - key: kv/data/dbot/controller-credentials
    name: DEX_SAML_SSO_URL
    property: DEX_SAML_SSO_URL
  - key: kv/data/dbot/controller-credentials
    name: DEX_SAML_SSO_ISSUER
    property: DEX_SAML_SSO_ISSUER
  - key: kv/data/dbot/controller-credentials
    name: ca.crt
    property: DEX_SAML_CA
  kvVersion: 2

---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: dbot-hook-credentials
spec:
  backendType: vault
  data:
  - key: kv/data/dbot/hook-credentials
    name: HOOK_GITLAB_API_TOKEN
    property: HOOK_GITLAB_API_TOKEN
  - key: kv/data/dbot/hook-credentials
    name: HOOK_ARGOCD_API_TOKEN
    property: HOOK_ARGOCD_API_TOKEN
  - key: kv/data/dbot/hook-credentials
    name: HOOK_WEBHOOK_TOKEN
    property: HOOK_WEBHOOK_TOKEN
  kvVersion: 2