{{ $global := .Values.dbot.global -}}
{{ $values := .Values.dbot.controller -}}
# In nginx config map
# client-header-buffer-size: 64k
# use-http2: 'false'
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    external-dns.alpha.kubernetes.io/hostname: api.dbot.{{$global.domain}}.
    kubernetes.io/ingress.class: traefik-int
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: true

  labels:
    app: dbot-controller
    project: dbot
  name: dbot-controller
  namespace: dbot
spec:
  rules:
    - host: api.dbot.{{$global.domain}}
      http:
        paths:
          - backend:
              service:
                name: dbot-controller
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - api.dbot.{{$global.domain}}
      secretName: api.dbot.ingress.tls
