---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dbot-front-role
  labels:
    app: dbot-front
    project: dbot
  namespace: dbot
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  verbs:
  - list
  resources:
  - pods

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dbot-front-rb
  namespace: dbot
  labels:
    app: dbot-front
    project: dbot
subjects:
- kind: ServiceAccount
  name: dbot-front
  namespace: dbot
roleRef:
  kind: ClusterRole
  name: dbot-front-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbot-front
  namespace: dbot
  labels:
    app: dbot-front
    project: dbot

