---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbot-dex-role
  labels:
    app: dbot-dex
    project: dbot
rules:
- apiGroups:
  - dex.coreos.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dbot-dex-rb
  labels:
    app: dbot-dex
    project: dbot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dbot-dex-role
subjects:
- kind: ServiceAccount
  name: dbot-dex
  namespace: dbot

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dbot-dex
  namespace: dbot
  labels:
    app: dbot-dex
    project: dbot