{{ $global := .Values.dbot.global -}}
{{ $values := .Values.dbot.rabbitmq -}}

{{- if $values.secret.create }}  
---
apiVersion: v1
kind: Secret
metadata:
  name: dbot-default-user
type: Opaque
stringData:
{{- toYaml $values.secret | nindent 2 }}
{{- end }}