{{ $global := .Values.dbot.global -}}
{{ $values := .Values.dbot.controller -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: dbot-controller-credentials
type: Opaque
stringData:
{{- toYaml $values.credentials | nindent 2 }}