{{ $global := .Values.dbot.global -}}
{{ $values := .Values.dbot.rabbitmq -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
stringData:
{{- toYaml $values.credentials | nindent 2 }}