apiVersion: v1
kind: Service
metadata:
  labels:
    app: dbot-controller
    project: dbot
  name: dbot-controller
  namespace: dbot
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: dbot-controller
  sessionAffinity: None
  type: ClusterIP
