dbot:
  global:
    image:
      repo: ghcr.io/dbot-group
      #tag: v0.2.0
    domain: dev.dbot-group.com
  dex:
    credentials:
      SAML_SSO_URL: ""
      SAML_SSO_ISSUER: ""
      SAML_CA: ""
  rabbitmq:
    deploy: true
    secret:
      create: false
      host: ""
      username: ""
      password: ""
  controller:
    credentials:
      HOOK_SERVICE_TOKEN: ""
      GITLAB_API_TOKEN: ""
    env:
      - name: DEBUG_REQUESTS
        value: "false"
      - name: DUMP_JSON_FILE
        value: "false"
      - name: AGENT_AUTH_ENABLED
        value: "false"
      - name: SSO_AUTH_ENABLED
        value: "true"
      - name: HOOK_SERVICE_ENABLED
        value: "true"
      - name: HOOK_SERVICE_URL
        value: "http://dbot-hook.dbot:8292"
    resources:
      limits:
        memory: "2Gi"
        cpu: 1
      requests:
        memory: "512Mi"
        cpu: 200m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - app
            - matchExpressions:
                - key: pool-type
                  operator: In
                  values:
                    - app
  hook:
    enabled: false

  workflowcontroller:
    enabled: false
    env:
      - name: WORKFLOW_CONTROLLER_DUMMY_WORKER_ENABLED
        value: "false"
    resources:
      limits:
        memory: "2Gi"
        cpu: 1
      requests:
        memory: "512Mi"
        cpu: 200m
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - app
            - matchExpressions:
                - key: pool-type
                  operator: In
                  values:
                    - app
