dbot:
  global:
    image:
      repo: ghcr.io/dbot-group
      # tag: v0.2.0
    domain: mgmt-dev.promarkcloud.com
  controller:
    env:
      - name: DEBUG_REQUESTS
        value: "false"
      - name: DUMP_JSON_FILE
        value: "false"
      - name: AGENT_AUTH
        value: "false"
      - name: SSO_AUTH
        value: "false"
      - name: WORKFLOW_CONTROLLER_ENABLED
        value: "true"
      - name: HOOK_SERVICE_ENABLED
        value: "true"
      - name: HOOK_SERVICE_URL
        value: "http://dbot-hook.dbot:8292"
    resources:
      limits:
        memory: "3Gi"
        cpu: 4
      requests:
        memory: "1Gi"
        cpu: 2
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - app
            - matchExpressions:
                - key: pool-type
                  operator: In
                  values:
                    - app

  workflowcontroller:
    env:
      - name: WORKFLOW_CONTROLLER_ENABLED
        value: "true"
      - name: WORKFLOW_CONTROLLER_DUMMY_WORKER_ENABLED
        value: "false"
    resources:
      limits:
        memory: "2Gi"
        cpu: 2
      requests:
        memory: "512Mi"
        cpu: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - app
            - matchExpressions:
                - key: pool-type
                  operator: In
                  values:
                    - app
